[build]
  command = "npm install --legacy-peer-deps --include=optional && npm rebuild @parcel/watcher && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200